name: Nightly Build
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Build with Gradle
        run: ./gradlew build

      - name: Generate tag
        id: tag
        run: echo "tag=nightly-$(date -u +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Delete old nightly releases
        uses: dev-drprasad/delete-older-releases@v0.3.4
        with:
          repo: ${{ github.repository }}
          tag_prefix: nightly
          keep_latest: 3
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ steps.tag.outputs.tag }}
          name: Nightly Build ${{ steps.tag.outputs.tag }}
          prerelease: true
          fail_on_unmatched_files: true
          files: |
            ./build/libs/*.jar
